export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
}

export interface Shop {
  id: string;
  name: string;
  image: string;
  location: string;
  address: string;
  lat: number;
  lng: number;
  rating: number;
  specialty: string;
  type: 'coffee' | 'smoothie' | 'both' | 'bakery' | 'chain';
  isNationalChain?: boolean;
  menu: Product[];
}

export interface TeamMember {
  id: string;
  name: string;
  role: string;
  initials: string;
  pin: string;
}

export const TEAM_MEMBERS: TeamMember[] = [
  { id: '1', name: 'Only', role: 'Founder', initials: 'O', pin: '1111' },
  { id: '2', name: 'Pete', role: 'Finance Manager', initials: 'P', pin: '1234' },
  { id: '3', name: 'Brian', role: 'Regional VP', initials: 'B', pin: '2345' },
  { id: '4', name: 'Megan', role: 'General Manager', initials: 'M', pin: '3456' },
  { id: '5', name: 'Brooke K', role: 'HR Manager', initials: 'BK', pin: '4567' },
  { id: '6', name: 'Jay', role: 'Purchasing Manager', initials: 'J', pin: '5678' },
  { id: '7', name: 'AJ', role: 'Warehouse Manager', initials: 'AJ', pin: '6789' },
];

export const COFFEE_SHOPS: Shop[] = [
  {
    id: 'crema',
    name: 'Crema Coffee Roasters',
    image: '/attached_assets/generated_images/crema_coffee_roasters_interior.png',
    location: 'Downtown Nashville',
    address: '15 Hermitage Ave, Nashville, TN 37210',
    lat: 36.1587,
    lng: -86.7760,
    rating: 4.9,
    specialty: 'Single Origin Pour Over',
    type: 'coffee',
    menu: [
      { id: 'c1', name: 'Seasonal Pour Over', description: 'Ethiopian Yirgacheffe', price: 5.50, category: 'Coffee' },
      { id: 'c2', name: 'Coffee Soda', description: 'Espresso, soda water, orange peel', price: 6.00, category: 'Specialty' },
      { id: 'c3', name: 'Iced Americano', description: 'Double shot over ice', price: 4.50, category: 'Coffee' },
      { id: 'c4', name: 'Honey Lavender Latte', description: 'Local honey, lavender syrup', price: 6.50, category: 'Specialty' },
      { id: 'c5', name: 'Fruit Refresher', description: 'Passion fruit, mango, green tea', price: 5.50, category: 'Fruit Drinks' },
      { id: 'c6', name: 'Avocado Toast', description: 'Sourdough, radish, chili oil', price: 12.00, category: 'Food' },
      { id: 'c7', name: 'Carafe Service (10 Cups)', description: 'Meeting size freshly brewed coffee', price: 45.00, category: 'Catering' },
      { id: 'c8', name: 'Assorted Pastry Box (12)', description: 'Croissants, muffins, scones', price: 48.00, category: 'Catering' },
    ]
  },
  {
    id: 'barista-parlor',
    name: 'Barista Parlor',
    image: '/attached_assets/generated_images/barista_parlor_interior.png',
    location: 'The Gulch',
    address: '519 Gallatin Ave, Nashville, TN 37206',
    lat: 36.1815,
    lng: -86.7480,
    rating: 4.8,
    specialty: 'Artisan Espresso',
    type: 'coffee',
    menu: [
      { id: 'b1', name: 'Bourbon Vanilla Latte', description: 'House-made vanilla syrup', price: 6.50, category: 'Coffee' },
      { id: 'b2', name: 'Whiskey Caramel', description: 'Signature sweet espresso drink', price: 7.00, category: 'Specialty' },
      { id: 'b3', name: 'Cold Brew', description: '24-hour steeped, smooth finish', price: 5.00, category: 'Coffee' },
      { id: 'b4', name: 'Matcha Lemonade', description: 'Ceremonial matcha, fresh lemon', price: 6.00, category: 'Fruit Drinks' },
      { id: 'b5', name: 'Berry Hibiscus Refresher', description: 'Mixed berries, hibiscus tea', price: 5.50, category: 'Fruit Drinks' },
      { id: 'b6', name: 'Biscuit Sandwich', description: 'Egg, cheese, bacon', price: 9.00, category: 'Food' },
      { id: 'b7', name: 'Pastry Box (Dozen)', description: 'Assorted morning pastries', price: 55.00, category: 'Catering' },
      { id: 'b8', name: 'Coffee Bar Setup', description: 'Full service for 20 people', price: 150.00, category: 'Catering' },
    ]
  },
  {
    id: 'frothy-monkey',
    name: 'Frothy Monkey',
    image: '/attached_assets/generated_images/frothy_monkey_interior.png',
    location: '12 South',
    address: '2509 12th Ave S, Nashville, TN 37204',
    lat: 36.1275,
    lng: -86.7892,
    rating: 4.7,
    specialty: 'Breakfast Blend',
    type: 'both',
    menu: [
      { id: 'f1', name: 'Monkey Mocha', description: 'Banana syrup, chocolate', price: 6.00, category: 'Specialty' },
      { id: 'f2', name: 'Drip Coffee', description: 'House blend, bottomless option', price: 4.00, category: 'Coffee' },
      { id: 'f3', name: 'Tropical Smoothie', description: 'Mango, pineapple, coconut milk', price: 7.00, category: 'Smoothies' },
      { id: 'f4', name: 'Berry Blast Smoothie', description: 'Strawberry, blueberry, banana', price: 7.00, category: 'Smoothies' },
      { id: 'f5', name: 'Green Machine', description: 'Spinach, banana, almond butter', price: 7.50, category: 'Smoothies' },
      { id: 'f6', name: 'Fresh Squeezed OJ', description: 'Made to order', price: 5.00, category: 'Fruit Drinks' },
      { id: 'f7', name: 'Loaded Oatmeal', description: 'Berries, nuts, brown sugar', price: 8.00, category: 'Food' },
      { id: 'f8', name: 'Meeting Traveler', description: '96oz of fresh coffee', price: 35.00, category: 'Catering' },
      { id: 'f9', name: 'Smoothie Bar (20 servings)', description: 'Build your own smoothie station', price: 120.00, category: 'Catering' },
    ]
  },
  {
    id: 'drug-store',
    name: 'Drug Store Coffee',
    image: '/attached_assets/generated_images/drug_store_coffee_interior.png',
    location: 'Noelle Hotel',
    address: '200 4th Ave N, Nashville, TN 37219',
    lat: 36.1627,
    lng: -86.7785,
    rating: 4.9,
    specialty: 'Premium Experience',
    type: 'coffee',
    menu: [
      { id: 'd1', name: 'Cortado', description: 'Equal parts espresso and milk', price: 4.50, category: 'Coffee' },
      { id: 'd2', name: 'Matcha Latte', description: 'Ceremonial grade matcha', price: 6.00, category: 'Tea' },
      { id: 'd3', name: 'Citrus Cold Brew', description: 'Orange zest infused', price: 6.00, category: 'Specialty' },
      { id: 'd4', name: 'Lavender Lemonade', description: 'House-made, refreshing', price: 5.00, category: 'Fruit Drinks' },
      { id: 'd5', name: 'Croissant', description: 'Butter croissant', price: 5.00, category: 'Food' },
      { id: 'd6', name: 'Executive Breakfast', description: 'Assorted pastries and fruit', price: 120.00, category: 'Catering' },
      { id: 'd7', name: 'Premium Coffee Service', description: 'White glove for 15 guests', price: 175.00, category: 'Catering' },
    ]
  },
  {
    id: 'steadfast',
    name: 'Steadfast Coffee',
    image: '/attached_assets/generated_images/crema_coffee_roasters_interior.png',
    location: 'East Nashville',
    address: '630 Fatherland St, Nashville, TN 37206',
    lat: 36.1780,
    lng: -86.7520,
    rating: 4.8,
    specialty: 'Direct Trade Roasting',
    type: 'coffee',
    menu: [
      { id: 'st1', name: 'House Espresso', description: 'Rich, balanced blend', price: 4.00, category: 'Coffee' },
      { id: 'st2', name: 'Oat Milk Latte', description: 'Creamy oat milk, espresso', price: 6.00, category: 'Coffee' },
      { id: 'st3', name: 'Nitro Cold Brew', description: 'Creamy nitrogen-infused', price: 5.50, category: 'Coffee' },
      { id: 'st4', name: 'Chai Latte', description: 'House-spiced chai', price: 5.50, category: 'Tea' },
      { id: 'st5', name: 'Lemon Ginger Tea', description: 'Fresh and soothing', price: 4.50, category: 'Tea' },
      { id: 'st6', name: 'Breakfast Burrito', description: 'Eggs, cheese, peppers', price: 10.00, category: 'Food' },
      { id: 'st7', name: 'Office Carafe (12 cups)', description: 'Fresh brewed for meetings', price: 50.00, category: 'Catering' },
    ]
  },
  {
    id: 'dose',
    name: 'Dose Coffee',
    image: '/attached_assets/generated_images/barista_parlor_interior.png',
    location: 'Berry Hill',
    address: '2800 Bransford Ave, Nashville, TN 37204',
    lat: 36.1189,
    lng: -86.7680,
    rating: 4.6,
    specialty: 'Quick Service Excellence',
    type: 'coffee',
    menu: [
      { id: 'do1', name: 'Classic Latte', description: 'Perfect espresso balance', price: 5.00, category: 'Coffee' },
      { id: 'do2', name: 'Caramel Macchiato', description: 'Vanilla, caramel drizzle', price: 5.50, category: 'Specialty' },
      { id: 'do3', name: 'Iced Mocha', description: 'Chocolate, espresso, milk', price: 5.50, category: 'Coffee' },
      { id: 'do4', name: 'Strawberry Acai Refresher', description: 'Light and fruity', price: 5.00, category: 'Fruit Drinks' },
      { id: 'do5', name: 'Protein Smoothie', description: 'Banana, peanut butter, protein', price: 7.50, category: 'Smoothies' },
      { id: 'do6', name: 'Quick Bite Box', description: 'Muffin, fruit, yogurt', price: 8.00, category: 'Food' },
      { id: 'do7', name: 'Team Coffee Box', description: '10 cups + cream & sugar', price: 40.00, category: 'Catering' },
    ]
  },
  {
    id: 'humphreys',
    name: 'Humphreys Street Coffee',
    image: '/attached_assets/generated_images/frothy_monkey_interior.png',
    location: 'Wedgewood-Houston',
    address: '611 Humphreys St, Nashville, TN 37203',
    lat: 36.1385,
    lng: -86.7835,
    rating: 4.7,
    specialty: 'Neighborhood Vibes',
    type: 'both',
    menu: [
      { id: 'h1', name: 'House Drip', description: 'Rotating single origin', price: 3.50, category: 'Coffee' },
      { id: 'h2', name: 'Honey Oat Latte', description: 'Sweet and creamy', price: 6.00, category: 'Specialty' },
      { id: 'h3', name: 'Iced Tea', description: 'Sweet or unsweet', price: 3.00, category: 'Tea' },
      { id: 'h4', name: 'Peach Mango Smoothie', description: 'Fresh fruit blend', price: 6.50, category: 'Smoothies' },
      { id: 'h5', name: 'Açaí Bowl', description: 'Topped with granola, fruit', price: 10.00, category: 'Food' },
      { id: 'h6', name: 'Bagel & Schmear', description: 'Cream cheese, your choice', price: 5.00, category: 'Food' },
      { id: 'h7', name: 'Brunch Catering', description: 'Coffee + pastries for 15', price: 85.00, category: 'Catering' },
    ]
  },
  {
    id: 'smoothie-king',
    name: 'Smoothie King',
    image: '/attached_assets/generated_images/drug_store_coffee_interior.png',
    location: 'Multiple Nashville Locations',
    address: '2126 Abbott Martin Rd, Nashville, TN 37215',
    lat: 36.1045,
    lng: -86.8165,
    rating: 4.5,
    specialty: 'Fitness & Wellness Smoothies',
    type: 'smoothie',
    menu: [
      { id: 'sk1', name: 'Hulk (Strawberry)', description: 'Weight gain blend', price: 7.99, category: 'Smoothies' },
      { id: 'sk2', name: 'Lean1 Vanilla', description: 'Meal replacement smoothie', price: 7.49, category: 'Smoothies' },
      { id: 'sk3', name: 'Gladiator Chocolate', description: '45g protein power', price: 8.49, category: 'Smoothies' },
      { id: 'sk4', name: 'Caribbean Way', description: 'Strawberry, banana, papaya', price: 6.99, category: 'Smoothies' },
      { id: 'sk5', name: 'Pineapple Surf', description: 'Tropical pineapple blend', price: 6.99, category: 'Smoothies' },
      { id: 'sk6', name: 'Immune Builder', description: 'Vitamin C, zinc boost', price: 7.49, category: 'Smoothies' },
      { id: 'sk7', name: 'Angel Food', description: 'Light and fruity', price: 6.49, category: 'Smoothies' },
      { id: 'sk8', name: 'Team Fuel Pack (10)', description: '10 medium smoothies', price: 65.00, category: 'Catering' },
      { id: 'sk9', name: 'Wellness Bar Setup', description: 'Smoothie bar for 20', price: 140.00, category: 'Catering' },
    ]
  },
  {
    id: 'tropical-smoothie',
    name: 'Tropical Smoothie Cafe',
    image: '/attached_assets/generated_images/crema_coffee_roasters_interior.png',
    location: 'Green Hills',
    address: '3900 Hillsboro Pike, Nashville, TN 37215',
    lat: 36.1012,
    lng: -86.8098,
    rating: 4.4,
    specialty: 'Tropical Flavors & Wraps',
    type: 'both',
    menu: [
      { id: 'ts1', name: 'Sunrise Sunset', description: 'Strawberry, pineapple, mango', price: 6.49, category: 'Smoothies' },
      { id: 'ts2', name: 'Bahama Mama', description: 'Strawberry, pineapple, coconut', price: 6.49, category: 'Smoothies' },
      { id: 'ts3', name: 'Detox Island Green', description: 'Spinach, kale, mango, banana', price: 6.99, category: 'Smoothies' },
      { id: 'ts4', name: 'Peanut Butter Cup', description: 'Chocolate, peanut butter', price: 6.99, category: 'Smoothies' },
      { id: 'ts5', name: 'Acai Berry Boost', description: 'Acai, blueberry, strawberry', price: 7.29, category: 'Smoothies' },
      { id: 'ts6', name: 'Fresh Lemonade', description: 'Made fresh daily', price: 3.99, category: 'Fruit Drinks' },
      { id: 'ts7', name: 'Chicken Caesar Wrap', description: 'Grilled chicken, romaine', price: 9.99, category: 'Food' },
      { id: 'ts8', name: 'Meeting Smoothie Bundle', description: '12 smoothies mixed', price: 72.00, category: 'Catering' },
    ]
  },
  {
    id: 'jamba',
    name: 'Jamba',
    image: '/attached_assets/generated_images/barista_parlor_interior.png',
    location: 'Cool Springs',
    address: '1800 Galleria Blvd, Franklin, TN 37067',
    lat: 35.9625,
    lng: -86.8187,
    rating: 4.3,
    specialty: 'Classic Smoothies & Bowls',
    type: 'smoothie',
    menu: [
      { id: 'j1', name: 'Strawberry Wild', description: 'Strawberry, apple juice', price: 6.29, category: 'Smoothies' },
      { id: 'j2', name: 'Mango-a-Go-Go', description: 'Mango, pineapple sherbet', price: 6.59, category: 'Smoothies' },
      { id: 'j3', name: 'Razzmatazz', description: 'Raspberry, strawberry, banana', price: 6.59, category: 'Smoothies' },
      { id: 'j4', name: 'Orange Dream Machine', description: 'Orange sherbet, vanilla', price: 6.29, category: 'Smoothies' },
      { id: 'j5', name: 'Protein Berry Workout', description: 'Whey protein, berries', price: 7.49, category: 'Smoothies' },
      { id: 'j6', name: 'Açaí Primo Bowl', description: 'Açaí, strawberry, banana', price: 9.49, category: 'Bowls' },
      { id: 'j7', name: 'Fresh Squeezed OJ', description: 'Made to order', price: 4.99, category: 'Fruit Drinks' },
      { id: 'j8', name: 'Office Fuel Pack', description: '8 smoothies + snacks', price: 58.00, category: 'Catering' },
    ]
  },
  {
    id: 'just-love',
    name: 'Just Love Coffee Cafe',
    image: '/attached_assets/generated_images/frothy_monkey_interior.png',
    location: 'Franklin',
    address: '330 Franklin Rd, Franklin, TN 37069',
    lat: 35.9256,
    lng: -86.8684,
    rating: 4.6,
    specialty: 'Community & Great Coffee',
    type: 'both',
    menu: [
      { id: 'jl1', name: 'Love Latte', description: 'Signature house latte', price: 5.50, category: 'Coffee' },
      { id: 'jl2', name: 'Frozen Mocha', description: 'Blended chocolate coffee', price: 6.00, category: 'Specialty' },
      { id: 'jl3', name: 'Nashville Hot Latte', description: 'Spicy cayenne kick', price: 6.00, category: 'Specialty' },
      { id: 'jl4', name: 'Berry Blast Smoothie', description: 'Mixed berry goodness', price: 6.50, category: 'Smoothies' },
      { id: 'jl5', name: 'Peanut Butter Banana', description: 'Classic combo', price: 6.50, category: 'Smoothies' },
      { id: 'jl6', name: 'Chicken Salad Sandwich', description: 'House recipe', price: 10.00, category: 'Food' },
      { id: 'jl7', name: 'Board Meeting Package', description: 'Coffee, pastries, fruit for 12', price: 95.00, category: 'Catering' },
    ]
  },
  {
    id: 'eighth-son',
    name: '8th & Roast',
    image: '/attached_assets/generated_images/drug_store_coffee_interior.png',
    location: 'Berry Hill',
    address: '2108 8th Ave S, Nashville, TN 37204',
    lat: 36.1315,
    lng: -86.7825,
    rating: 4.8,
    specialty: 'Small Batch Roasting',
    type: 'coffee',
    menu: [
      { id: 'er1', name: 'Espresso', description: 'Double shot perfection', price: 3.50, category: 'Coffee' },
      { id: 'er2', name: 'Cappuccino', description: 'Traditional Italian style', price: 5.00, category: 'Coffee' },
      { id: 'er3', name: 'Affogato', description: 'Espresso over gelato', price: 6.50, category: 'Specialty' },
      { id: 'er4', name: 'Chai Tea Latte', description: 'Spiced and creamy', price: 5.50, category: 'Tea' },
      { id: 'er5', name: 'Fresh Fruit Cup', description: 'Seasonal selection', price: 5.00, category: 'Food' },
      { id: 'er6', name: 'Artisan Toast', description: 'Avocado or almond butter', price: 8.00, category: 'Food' },
      { id: 'er7', name: 'Roaster\'s Choice Carafe', description: '12 cups premium roast', price: 55.00, category: 'Catering' },
    ]
  },
  {
    id: 'starbucks-downtown',
    name: 'Starbucks',
    image: '/attached_assets/generated_images/crema_coffee_roasters_interior.png',
    location: 'Downtown Nashville',
    address: '315 Broadway, Nashville, TN 37201',
    lat: 36.1620,
    lng: -86.7765,
    rating: 4.2,
    specialty: 'Global Coffee Standard',
    type: 'chain',
    isNationalChain: true,
    menu: [
      { id: 'sb1', name: 'Pike Place Roast', description: 'Smooth, well-rounded blend', price: 3.45, category: 'Coffee' },
      { id: 'sb2', name: 'Caffe Latte', description: 'Espresso with steamed milk', price: 5.75, category: 'Coffee' },
      { id: 'sb3', name: 'Caramel Macchiato', description: 'Vanilla, caramel, espresso', price: 6.25, category: 'Specialty' },
      { id: 'sb4', name: 'Pumpkin Spice Latte', description: 'Seasonal favorite', price: 6.75, category: 'Specialty' },
      { id: 'sb5', name: 'Cold Brew', description: 'Slow-steeped, smooth', price: 4.95, category: 'Coffee' },
      { id: 'sb6', name: 'Pink Drink', description: 'Strawberry Acai Refresher', price: 5.95, category: 'Fruit Drinks' },
      { id: 'sb7', name: 'Iced Matcha Latte', description: 'Matcha green tea blend', price: 5.75, category: 'Tea' },
      { id: 'sb8', name: 'Bacon Gouda Sandwich', description: 'Applewood bacon, egg', price: 5.95, category: 'Food' },
      { id: 'sb9', name: 'Coffee Traveler (96oz)', description: 'Serves 12 (8oz cups)', price: 21.95, category: 'Catering' },
      { id: 'sb10', name: 'Assorted Pastry Tray', description: '12 assorted pastries', price: 32.00, category: 'Catering' },
    ]
  },
  {
    id: 'starbucks-green-hills',
    name: 'Starbucks',
    image: '/attached_assets/generated_images/crema_coffee_roasters_interior.png',
    location: 'Green Hills',
    address: '2126 Abbott Martin Rd, Nashville, TN 37215',
    lat: 36.1048,
    lng: -86.8168,
    rating: 4.1,
    specialty: 'Global Coffee Standard',
    type: 'chain',
    isNationalChain: true,
    menu: [
      { id: 'sbg1', name: 'Pike Place Roast', description: 'Smooth, well-rounded blend', price: 3.45, category: 'Coffee' },
      { id: 'sbg2', name: 'Caffe Latte', description: 'Espresso with steamed milk', price: 5.75, category: 'Coffee' },
      { id: 'sbg3', name: 'Caramel Macchiato', description: 'Vanilla, caramel, espresso', price: 6.25, category: 'Specialty' },
      { id: 'sbg4', name: 'Nitro Cold Brew', description: 'Nitrogen-infused smooth', price: 5.75, category: 'Coffee' },
      { id: 'sbg5', name: 'Mango Dragonfruit Refresher', description: 'Tropical and refreshing', price: 5.45, category: 'Fruit Drinks' },
      { id: 'sbg6', name: 'Cheese Danish', description: 'Flaky pastry', price: 3.75, category: 'Food' },
      { id: 'sbg7', name: 'Coffee Traveler (96oz)', description: 'Serves 12 (8oz cups)', price: 21.95, category: 'Catering' },
    ]
  },
  {
    id: 'dunkin-broadway',
    name: 'Dunkin\'',
    image: '/attached_assets/generated_images/barista_parlor_interior.png',
    location: 'Lower Broadway',
    address: '106 Broadway, Nashville, TN 37201',
    lat: 36.1615,
    lng: -86.7755,
    rating: 4.0,
    specialty: 'America Runs on Dunkin\'',
    type: 'chain',
    isNationalChain: true,
    menu: [
      { id: 'dk1', name: 'Original Blend Coffee', description: 'Smooth and balanced', price: 2.79, category: 'Coffee' },
      { id: 'dk2', name: 'Iced Coffee', description: 'Refreshing and bold', price: 3.49, category: 'Coffee' },
      { id: 'dk3', name: 'Caramel Swirl Latte', description: 'Creamy caramel goodness', price: 5.29, category: 'Specialty' },
      { id: 'dk4', name: 'Frozen Coffee', description: 'Blended coffee treat', price: 4.99, category: 'Specialty' },
      { id: 'dk5', name: 'Glazed Donut', description: 'Classic glazed ring', price: 1.69, category: 'Food' },
      { id: 'dk6', name: 'Boston Kreme Donut', description: 'Chocolate topped, cream filled', price: 1.89, category: 'Food' },
      { id: 'dk7', name: 'Bacon Egg & Cheese', description: 'On croissant or bagel', price: 5.49, category: 'Food' },
      { id: 'dk8', name: 'Box O\' Joe (10 cups)', description: 'Hot coffee for groups', price: 18.99, category: 'Catering' },
      { id: 'dk9', name: 'Dozen Donuts', description: 'Assorted varieties', price: 15.99, category: 'Catering' },
      { id: 'dk10', name: 'Munchkins (50 count)', description: 'Donut hole assortment', price: 12.99, category: 'Catering' },
    ]
  },
  {
    id: 'dunkin-midtown',
    name: 'Dunkin\'',
    image: '/attached_assets/generated_images/barista_parlor_interior.png',
    location: 'Midtown Nashville',
    address: '1801 West End Ave, Nashville, TN 37203',
    lat: 36.1528,
    lng: -86.8018,
    rating: 4.1,
    specialty: 'America Runs on Dunkin\'',
    type: 'chain',
    isNationalChain: true,
    menu: [
      { id: 'dkm1', name: 'Original Blend Coffee', description: 'Smooth and balanced', price: 2.79, category: 'Coffee' },
      { id: 'dkm2', name: 'Cold Brew', description: 'Slow steeped for hours', price: 4.29, category: 'Coffee' },
      { id: 'dkm3', name: 'Iced Matcha Latte', description: 'Sweetened matcha', price: 5.29, category: 'Tea' },
      { id: 'dkm4', name: 'Strawberry Dragonfruit Refresher', description: 'Fruity and energizing', price: 4.49, category: 'Fruit Drinks' },
      { id: 'dkm5', name: 'Jelly Donut', description: 'Powdered with jelly filling', price: 1.89, category: 'Food' },
      { id: 'dkm6', name: 'Box O\' Joe (10 cups)', description: 'Hot coffee for groups', price: 18.99, category: 'Catering' },
      { id: 'dkm7', name: 'Bagel & Schmear Bundle', description: '6 bagels + cream cheese', price: 14.99, category: 'Catering' },
    ]
  },
  {
    id: 'dutch-bros-hermitage',
    name: 'Dutch Bros Coffee',
    image: '/attached_assets/generated_images/frothy_monkey_interior.png',
    location: 'Hermitage',
    address: '4901 Lebanon Pike, Hermitage, TN 37076',
    lat: 36.1725,
    lng: -86.6115,
    rating: 4.7,
    specialty: 'Drive-Thru Coffee & Energy',
    type: 'chain',
    isNationalChain: true,
    menu: [
      { id: 'db1', name: 'Dutch Bros Blue Rebel', description: 'Energy drink base', price: 4.75, category: 'Specialty' },
      { id: 'db2', name: 'Caramelizer', description: 'Caramel mocha breve', price: 5.75, category: 'Specialty' },
      { id: 'db3', name: 'Golden Eagle', description: 'Vanilla, caramel breve', price: 5.75, category: 'Specialty' },
      { id: 'db4', name: 'Annihilator', description: 'Chocolate macadamia nut', price: 5.75, category: 'Specialty' },
      { id: 'db5', name: 'Dutch Freeze', description: 'Blended coffee', price: 5.50, category: 'Specialty' },
      { id: 'db6', name: 'Rebel Energy Freeze', description: 'Blended energy drink', price: 5.50, category: 'Specialty' },
      { id: 'db7', name: 'Peach Rebel', description: 'Peach flavored energy', price: 4.75, category: 'Fruit Drinks' },
      { id: 'db8', name: 'Strawberry Lemonade', description: 'Fresh and sweet', price: 4.25, category: 'Fruit Drinks' },
      { id: 'db9', name: 'Party Pack (12 drinks)', description: 'Mixed drinks for team', price: 60.00, category: 'Catering' },
    ]
  },
  {
    id: 'dutch-bros-murfreesboro',
    name: 'Dutch Bros Coffee',
    image: '/attached_assets/generated_images/frothy_monkey_interior.png',
    location: 'Murfreesboro',
    address: '2930 S Church St, Murfreesboro, TN 37127',
    lat: 35.8200,
    lng: -86.3920,
    rating: 4.6,
    specialty: 'Drive-Thru Coffee & Energy',
    type: 'chain',
    isNationalChain: true,
    menu: [
      { id: 'dbm1', name: 'Dutch Bros Blue Rebel', description: 'Energy drink base', price: 4.75, category: 'Specialty' },
      { id: 'dbm2', name: 'White Chocolate Mocha', description: 'Creamy white mocha', price: 5.75, category: 'Specialty' },
      { id: 'dbm3', name: 'Kicker', description: 'Irish cream breve', price: 5.75, category: 'Specialty' },
      { id: 'dbm4', name: 'Cocomo', description: 'Coconut mocha', price: 5.75, category: 'Specialty' },
      { id: 'dbm5', name: 'Cold Brew', description: 'Smooth cold brew', price: 4.50, category: 'Coffee' },
      { id: 'dbm6', name: 'Mango Smoothie', description: 'Tropical blend', price: 5.50, category: 'Smoothies' },
      { id: 'dbm7', name: 'Office Rebel Pack', description: '10 energy drinks', price: 45.00, category: 'Catering' },
    ]
  },
  {
    id: 'crumbl-brentwood',
    name: 'Crumbl Cookies',
    image: '/attached_assets/generated_images/drug_store_coffee_interior.png',
    location: 'Brentwood',
    address: '330 Franklin Rd Suite 910, Brentwood, TN 37027',
    lat: 36.0318,
    lng: -86.7825,
    rating: 4.8,
    specialty: 'Rotating Gourmet Cookies',
    type: 'bakery',
    menu: [
      { id: 'cr1', name: 'Classic Pink Sugar', description: 'Signature almond sugar cookie', price: 4.48, category: 'Cookies' },
      { id: 'cr2', name: 'Chocolate Chip', description: 'Semi-sweet chocolate', price: 4.48, category: 'Cookies' },
      { id: 'cr3', name: 'Weekly Special #1', description: 'Rotating flavor', price: 4.78, category: 'Cookies' },
      { id: 'cr4', name: 'Weekly Special #2', description: 'Rotating flavor', price: 4.78, category: 'Cookies' },
      { id: 'cr5', name: 'Weekly Special #3', description: 'Rotating flavor', price: 4.78, category: 'Cookies' },
      { id: 'cr6', name: 'Weekly Special #4', description: 'Rotating flavor', price: 4.78, category: 'Cookies' },
      { id: 'cr7', name: '4-Pack Box', description: 'Choose your flavors', price: 17.92, category: 'Catering' },
      { id: 'cr8', name: '6-Pack Box', description: 'Half dozen assorted', price: 26.88, category: 'Catering' },
      { id: 'cr9', name: 'Party Box (12)', description: 'Full dozen for meetings', price: 53.76, category: 'Catering' },
      { id: 'cr10', name: 'Catering Tray (24)', description: 'Double dozen assorted', price: 99.99, category: 'Catering' },
    ]
  },
  {
    id: 'crumbl-green-hills',
    name: 'Crumbl Cookies',
    image: '/attached_assets/generated_images/drug_store_coffee_interior.png',
    location: 'Green Hills',
    address: '2126 Abbott Martin Rd #110, Nashville, TN 37215',
    lat: 36.1055,
    lng: -86.8175,
    rating: 4.7,
    specialty: 'Rotating Gourmet Cookies',
    type: 'bakery',
    menu: [
      { id: 'crg1', name: 'Classic Pink Sugar', description: 'Signature almond sugar cookie', price: 4.48, category: 'Cookies' },
      { id: 'crg2', name: 'Chocolate Chip', description: 'Semi-sweet chocolate', price: 4.48, category: 'Cookies' },
      { id: 'crg3', name: 'Weekly Special #1', description: 'Rotating flavor', price: 4.78, category: 'Cookies' },
      { id: 'crg4', name: 'Weekly Special #2', description: 'Rotating flavor', price: 4.78, category: 'Cookies' },
      { id: 'crg5', name: '4-Pack Box', description: 'Choose your flavors', price: 17.92, category: 'Catering' },
      { id: 'crg6', name: 'Party Box (12)', description: 'Full dozen for meetings', price: 53.76, category: 'Catering' },
    ]
  },
  {
    id: 'gigis-cupcakes',
    name: 'Gigi\'s Cupcakes',
    image: '/attached_assets/generated_images/crema_coffee_roasters_interior.png',
    location: '12 South',
    address: '2905 12th Ave S, Nashville, TN 37204',
    lat: 36.1218,
    lng: -86.7892,
    rating: 4.6,
    specialty: 'Gourmet Cupcakes',
    type: 'bakery',
    menu: [
      { id: 'gg1', name: 'Wedding Cake', description: 'White cake, buttercream', price: 4.25, category: 'Cupcakes' },
      { id: 'gg2', name: 'Midnight Magic', description: 'Chocolate lovers dream', price: 4.25, category: 'Cupcakes' },
      { id: 'gg3', name: 'Scarlet\'s Red Velvet', description: 'Cream cheese frosting', price: 4.25, category: 'Cupcakes' },
      { id: 'gg4', name: 'Triple Chocolate Torte', description: 'Chocolate on chocolate', price: 4.50, category: 'Cupcakes' },
      { id: 'gg5', name: 'Hunka Chunka Banana', description: 'Banana with peanut butter', price: 4.50, category: 'Cupcakes' },
      { id: 'gg6', name: 'Cookies & Cream', description: 'Oreo inspired', price: 4.50, category: 'Cupcakes' },
      { id: 'gg7', name: 'Half Dozen Box', description: '6 assorted cupcakes', price: 24.00, category: 'Catering' },
      { id: 'gg8', name: 'Dozen Box', description: '12 assorted cupcakes', price: 45.00, category: 'Catering' },
      { id: 'gg9', name: 'Two Dozen Tray', description: '24 mini cupcakes', price: 72.00, category: 'Catering' },
    ]
  },
  {
    id: 'christie-cookies',
    name: 'Christie Cookie Co.',
    image: '/attached_assets/generated_images/barista_parlor_interior.png',
    location: 'Downtown Nashville',
    address: '234 5th Ave N, Nashville, TN 37219',
    lat: 36.1662,
    lng: -86.7812,
    rating: 4.7,
    specialty: 'Nashville\'s Favorite Cookie',
    type: 'bakery',
    menu: [
      { id: 'cc1', name: 'Original Chocolate Chip', description: 'Nashville classic since 1985', price: 3.50, category: 'Cookies' },
      { id: 'cc2', name: 'Double Chocolate', description: 'Rich chocolate cookie', price: 3.50, category: 'Cookies' },
      { id: 'cc3', name: 'Oatmeal Raisin', description: 'Chewy and wholesome', price: 3.50, category: 'Cookies' },
      { id: 'cc4', name: 'Peanut Butter', description: 'Classic peanut butter', price: 3.50, category: 'Cookies' },
      { id: 'cc5', name: 'White Chocolate Macadamia', description: 'Tropical twist', price: 3.75, category: 'Cookies' },
      { id: 'cc6', name: 'Snickerdoodle', description: 'Cinnamon sugar coated', price: 3.50, category: 'Cookies' },
      { id: 'cc7', name: 'Half Dozen', description: '6 cookies your choice', price: 19.50, category: 'Catering' },
      { id: 'cc8', name: 'Dozen Box', description: '12 assorted cookies', price: 36.00, category: 'Catering' },
      { id: 'cc9', name: 'Meeting Bundle', description: '24 cookies + napkins', price: 68.00, category: 'Catering' },
    ]
  },
  {
    id: 'five-daughters',
    name: 'Five Daughters Bakery',
    image: '/attached_assets/generated_images/frothy_monkey_interior.png',
    location: '12 South',
    address: '1110 Caruthers Ave, Nashville, TN 37204',
    lat: 36.1205,
    lng: -86.7905,
    rating: 4.9,
    specialty: '100-Layer Donuts',
    type: 'bakery',
    menu: [
      { id: 'fd1', name: '100 Layer Donut', description: 'Croissant-donut hybrid', price: 5.95, category: 'Donuts' },
      { id: 'fd2', name: 'Maple Glaze', description: 'Pure maple glaze', price: 5.95, category: 'Donuts' },
      { id: 'fd3', name: 'Chocolate Sea Salt', description: 'Dark chocolate, fleur de sel', price: 5.95, category: 'Donuts' },
      { id: 'fd4', name: 'Raspberry Rose', description: 'Berry with rosewater', price: 5.95, category: 'Donuts' },
      { id: 'fd5', name: 'Paleo Donut', description: 'Gluten-free, dairy-free', price: 6.50, category: 'Donuts' },
      { id: 'fd6', name: 'Cinnamon Sugar', description: 'Classic coating', price: 5.95, category: 'Donuts' },
      { id: 'fd7', name: 'Seasonal Special', description: 'Rotating flavor', price: 6.25, category: 'Donuts' },
      { id: 'fd8', name: 'Half Dozen Box', description: '6 assorted 100-layer', price: 33.00, category: 'Catering' },
      { id: 'fd9', name: 'Dozen Box', description: '12 assorted donuts', price: 62.00, category: 'Catering' },
      { id: 'fd10', name: 'Brunch Spread', description: '18 donuts + coffee for 8', price: 110.00, category: 'Catering' },
    ]
  },
  {
    id: 'baked-bear',
    name: 'The Baked Bear',
    image: '/attached_assets/generated_images/drug_store_coffee_interior.png',
    location: 'Broadway',
    address: '143 2nd Ave N, Nashville, TN 37201',
    lat: 36.1628,
    lng: -86.7752,
    rating: 4.5,
    specialty: 'Custom Ice Cream Sandwiches',
    type: 'bakery',
    menu: [
      { id: 'bb1', name: 'Classic Cookie Sandwich', description: 'Choose cookies & ice cream', price: 7.50, category: 'Ice Cream' },
      { id: 'bb2', name: 'Brownie Sandwich', description: 'Fudge brownie with ice cream', price: 8.50, category: 'Ice Cream' },
      { id: 'bb3', name: 'Fresh Baked Cookie', description: 'Warm from oven', price: 3.50, category: 'Cookies' },
      { id: 'bb4', name: 'Brownie Square', description: 'Rich fudge brownie', price: 4.00, category: 'Brownies' },
      { id: 'bb5', name: 'Milkshake', description: 'Blended ice cream shake', price: 7.00, category: 'Ice Cream' },
      { id: 'bb6', name: 'Cookie Dozen', description: '12 assorted cookies', price: 38.00, category: 'Catering' },
      { id: 'bb7', name: 'Ice Cream Party (10)', description: '10 custom sandwiches', price: 70.00, category: 'Catering' },
    ]
  },
];

export const SERVICE_FEE_PERCENT = 0.15;
export const DELIVERY_COORDINATION_FEE = 5.00;
export const EXTENDED_DELIVERY_PREMIUM = 7.50;
export const EXTENDED_DELIVERY_RADIUS_MILES = 10;

export const SUBSCRIPTION_TIERS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 29,
    description: 'Perfect for small teams with occasional meetings',
    features: [
      '10 orders per month',
      'Standard 2-hour lead time',
      'Email support',
      '1 user account',
      '10% service fee discount'
    ],
    serviceFeeDiscount: 0.10,
    ordersIncluded: 10,
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 79,
    description: 'For growing businesses with regular client meetings',
    features: [
      '50 orders per month',
      'Priority scheduling',
      'Phone support',
      '5 user accounts',
      '50% service fee discount',
      'Free delivery coordination'
    ],
    serviceFeeDiscount: 0.50,
    ordersIncluded: 50,
    freeDelivery: true,
    highlight: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 199,
    description: 'Unlimited access for large organizations',
    features: [
      'Unlimited orders',
      'Dedicated account manager',
      'Custom integrations',
      'SLA guarantee',
      'Unlimited users',
      'No service fees',
      'Priority white-glove delivery'
    ],
    serviceFeeDiscount: 1.0,
    ordersIncluded: -1,
    freeDelivery: true,
  }
];

export const NASHVILLE_ZIP_COORDS: Record<string, { lat: number; lng: number }> = {
  '37201': { lat: 36.1627, lng: -86.7816 },
  '37202': { lat: 36.1627, lng: -86.7816 },
  '37203': { lat: 36.1498, lng: -86.7906 },
  '37204': { lat: 36.1159, lng: -86.7817 },
  '37205': { lat: 36.1145, lng: -86.8587 },
  '37206': { lat: 36.1877, lng: -86.7380 },
  '37207': { lat: 36.2152, lng: -86.7617 },
  '37208': { lat: 36.1805, lng: -86.8040 },
  '37209': { lat: 36.1561, lng: -86.8571 },
  '37210': { lat: 36.1360, lng: -86.7524 },
  '37211': { lat: 36.0722, lng: -86.7118 },
  '37212': { lat: 36.1357, lng: -86.8049 },
  '37213': { lat: 36.1714, lng: -86.7530 },
  '37214': { lat: 36.1714, lng: -86.6679 },
  '37215': { lat: 36.0906, lng: -86.8169 },
  '37216': { lat: 36.2067, lng: -86.7097 },
  '37217': { lat: 36.1177, lng: -86.6633 },
  '37218': { lat: 36.2153, lng: -86.8387 },
  '37219': { lat: 36.1658, lng: -86.7844 },
  '37220': { lat: 36.0696, lng: -86.7781 },
  '37221': { lat: 36.0624, lng: -86.8917 },
  '37067': { lat: 35.9625, lng: -86.8187 },
  '37069': { lat: 35.9256, lng: -86.8684 },
};
